# Generated by Django 3.2.9 on 2022-01-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_topic', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Notificação Mercado Pago',
                'verbose_name_plural': 'Notificações Mercado Pago',
                'ordering': ('id_topic',),
            },
        ),
    ]
