# Generated by Django 3.2.9 on 2022-01-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mercadopagonotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagonotification',
            name='json',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
