# Generated by Django 3.2.9 on 2022-01-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shopcar_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido'),
        ),
    ]
