# Generated by Django 3.2.9 on 2021-11-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211118_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_model',
            name='file',
            field=models.FileField(blank=True, upload_to='app/static/public/product_images/'),
        ),
    ]
