# Generated by Django 3.2.9 on 2022-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shopcar_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Valor do Pedido'),
            preserve_default=False,
        ),
    ]
