# Generated by Django 3.2.9 on 2022-01-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220130_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantity',
        ),
    ]
