# Generated by Django 3.2.9 on 2022-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pedido_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Valor do Pedido'),
        ),
    ]
