# Generated by Django 3.2.9 on 2021-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pedido_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido_produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('id_produto', models.CharField(max_length=55)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_produto',
            new_name='usuario',
        ),
    ]
