# Generated by Django 3.2.9 on 2022-01-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220128_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercadopagonotification',
            old_name='json',
            new_name='action',
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='api_version',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='application_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='date_created',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='id_notification',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='live_mode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mercadopagonotification',
            name='user_id',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
