# Generated by Django 3.2.9 on 2022-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220130_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='status',
            field=models.IntegerField(choices=[(1, 'carrinho'), (2, 'pedido')], default=1),
        ),
    ]
