# Generated by Django 3.2.9 on 2022-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pedido_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'approved'), (2, 'in_process'), (3, 'rejected')], default=2),
        ),
    ]
