# Generated by Django 3.2.9 on 2022-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220128_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagonotification',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
