# Generated by Django 3.2.9 on 2021-12-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211205_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='favorito',
        ),
    ]
