# Generated by Django 3.2.9 on 2022-01-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mercadopagonotification_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagonotification',
            name='date_created',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
