# Generated by Django 3.2.9 on 2022-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_favorito_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('title',), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='file',
        ),
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='desc',
            field=models.CharField(max_length=55, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título'),
        ),
    ]
