# Generated by Django 3.2.9 on 2022-01-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mercadopagonotification_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadopagonotification',
            name='date_created',
        ),
    ]
