# Generated by Django 3.2.9 on 2022-01-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220122_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shop_car',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='shop_car',
            old_name='id_user',
            new_name='user',
        ),
    ]
