# Generated by Django 3.2.9 on 2022-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220122_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_car',
            name='quantity',
            field=models.IntegerField(default=2, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
