# Generated by Django 3.2.9 on 2022-01-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mercadopagonotification_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mercadopagonotification',
            options={'ordering': ('created',), 'verbose_name': 'Notificação Mercado Pago', 'verbose_name_plural': 'Notificações Mercado Pago'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
        migrations.AddField(
            model_name='shopcar',
            name='status',
            field=models.CharField(choices=[(1, 'Carrinho'), (2, 'Pedido')], default='1', max_length=255, verbose_name='Status'),
        ),
    ]
