# Generated by Django 3.2.9 on 2022-01-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_shop_car_shopcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='quantity',
            field=models.CharField(max_length=2, verbose_name='Quantidade'),
        ),
    ]
