# Generated by Django 3.2.9 on 2021-11-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
