# Generated by Django 3.2.9 on 2021-11-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211114_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pedido',
            new_name='pedido_model',
        ),
        migrations.RenameModel(
            old_name='produto',
            new_name='produto_model',
        ),
        migrations.RenameModel(
            old_name='shop_car',
            new_name='shop_car_model',
        ),
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='UploadFile_model',
        ),
    ]
