# Generated by Django 3.2.9 on 2021-11-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shop_car_model_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_car_model',
            name='quantity',
        ),
    ]
