# Generated by Django 3.2.9 on 2021-11-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211116_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_model',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
