# Generated by Django 3.2.9 on 2021-11-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_produto_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_model',
            name='file',
            field=models.FileField(upload_to='app/uploads/product_images/'),
        ),
    ]
