# Generated by Django 3.2.9 on 2021-11-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211118_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_model',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pedido_model',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='produto_model',
            name='created',
        ),
        migrations.RemoveField(
            model_name='produto_model',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='shop_car_model',
            name='created',
        ),
        migrations.RemoveField(
            model_name='shop_car_model',
            name='updated',
        ),
    ]
